name: june_model
description: "the module show how to define a entity model in juneflow."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_model

version: 1.0.12

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  path_provider:
  styled_widget:

dev_dependencies:
  bot_toast_module:
  config_theme:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view: #@add
  june_view_more: #@add
  screenutil_module:
  theme_mode_changer:

flutter:
  assets:
    - assets/module/config_theme/
    - assets/module/june_model/
  uses-material-design: true