name: june_model
description: "the module show how to define a entity model in juneflow."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_model

version: 1.0.5

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  bot_toast: ^4.1.3
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_zoom_drawer: ^3.2.0
  gap: ^3.0.1
  go_router: ^13.2.4
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  june: ^0.8.8
  june_flow_util: ^0.8.19
  keyboard_attachable:  ^2.2.0
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.3
  styled_widget: ^0.4.1

dev_dependencies:
  bot_toast_module: ^0.1.2
  config_theme: ^0.0.3
  device_preview_module: ^1.0.0
  flutter_lints: ^3.0.2
  flutter_lints_module: ^1.0.1
  flutter_test:
    sdk: flutter
  hive_module: ^1.0.4 #@add
  june_view: #@add
  june_view_more: #@add
  screenutil_module:
  theme_mode_changer:

flutter:
  assets:
    - assets/module/june_model/
  uses-material-design: true